version: "3.9"

services:
  db:
    image: mariadb:11
    container_name: news_mariadb
    restart: always
    environment:
      MYSQL_DATABASE: news_db
      MYSQL_USER: newsuser
      MYSQL_PASSWORD: newsapp123
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    container_name: news_app_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DEBUG: "True"
      DATABASE_HOST: db
      DATABASE_NAME: news_db
      DATABASE_USER: newsuser
      DATABASE_PASSWORD: newsapp123

volumes:
  db_data:
