# Generated by Django 6.0.2 on 2026-04-03 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='publisher',
            name='users',
            field=models.ManyToManyField(related_name='publishers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='news.publisher'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('reader', 'Reader'), ('editor', 'Editor'), ('journalist', 'Journalist'), ('publisher', 'Publisher')], default='reader', max_length=20),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
